[project]
name = "doctor"
description = "Doctor project"
readme = "README.md"
requires-python = ">=3.8"
[project.optional-dependencies]
db-sqlalchemy = ["SQLAlchemy>=1.3"]
db-postgresql = ["psycopg2-binary>=2.9", "SQLAlchemy>=1.3"]
dev = ["pytest","pytest-cov","black","ruff","mypy"]

authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = []
dynamic = ["version"]

[project.scripts]
documentor = "src.commands:main"
db-migrate = "src.commands.migrate.schema:main"


[project.urls]
"Homepage" = "https://github.com/..."
"Bug Reports" = "https://github.com/.../issues"
"Source" = "https://github.com/..."

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
